# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('n', 'Not for loan')], default='a', max_length=1),
        ),
    ]
