# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover_id',
        ),
    ]
